### ISSUE TITLE
AttributeError: module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/fibad#108]
**Bug report**
@maxwest-uw is working with fibad and kbmod-ml, and ran into this error when trying to push changes. It's clearly lines in Fibad that are causing this:

> Traceback (most recent call last):
>   File "/astro/users/maxwest/fibad_script.py", line 7, in <module>
>     fibad_instance = fibad.Fibad(config_file="kbmod_fibad_config.toml")
>   File "/astro/users/maxwest/fibad/src/fibad/fibad.py", line 46, in __init__
>     self.config_manager = ConfigManager(runtime_config_filepath=config_file)
>   File "/astro/users/maxwest/fibad/src/fibad/config_utils.py", line 85, in __init__
>     self.external_library_config_paths = self._find_external_library_default_config_paths(
>   File "/astro/users/maxwest/fibad/src/fibad/config_utils.py", line 136, in _find_external_library_default_config_paths
>     default_configs |= ConfigManager._find_external_library_default_config_paths(value)
>   File "/astro/users/maxwest/fibad/src/fibad/config_utils.py", line 140, in _find_external_library_default_config_paths
>     if importlib.util.find_spec(external_library) is not None:
> AttributeError: module 'importlib' has no attribute 'util'

**Comment by drewoldag** [comment]
I spent some time trying to reproduce this locally on the command line and wasn't able to do so. Running the following on my local machine with Python 3.11 was fine:

```
import importlib
importlib.util.find_spec("asdf")
```

In some examples of people using find_spec, I see that they typically import the following:
```
import importlib
import importlib.util
...
```
So perhaps that is necessary on some systems?

I also took a look through the python code base to see if perhaps importing just importlib would not include `util`, but it does seem to include it. 

So I'll put together a little PR that adds the second import importlib.util statement and we can see if that fixes things.

**Comment by drewoldag** [comment]
Closed the PR that was associated with this issue since it's not clear that it's actually addressing the root cause. Will reopen the PR (or close this issue) after I have a chance to do a little more investigation with @maxwest-uw in the coming weeks.

**Comment by drewoldag** [comment]
I haven't had a chance to review this with @maxwest-uw, will try to do that before Jan 10

**Comment by drewoldag** [comment]
I've been working with kbmod_ml for several days now and haven't been able to reproduce this error. Going to close as won't do.

**Comment by drewoldag** [comment]
Max is still encountering this issue, so reopening and will fix shortly.

**Comment by drewoldag** [comment]
FWIW, this only seems to crop up when running on the Balder machine.

**Comment by drewoldag** [comment]
One final note - I was watching over Max's shoulder when I saw this error pop up. When I attempted to reproduce this in my baldur account in the default python 3.7 environment, it worked fine, but when I switched to an environment with kbmod, it failed. 

In default python 9.7 environment
```
>>> import importlib
>>> importlib.util  # works fine
```

In kbmod python 9.11 environment
```
>>> import importlib
>>> importlib.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'util'
```
