### ISSUE TITLE
CNN + CiFAR data produces error with training

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/fibad#83]
When attempting to train the example CNN with CiFAR data I am seeing the following error message produced:

```
Files already downloaded and verified
2024-10-07 12:02:49,563 ignite.distributed.auto.auto_dataloader INFO: Use data loader kwargs for dataset 'Dataset CifarDataSet': 
	{'batch_size': 4, 'shuffle': True, 'num_workers': 1, 'pin_memory': False}
[2024-10-07 12:02:49,571 fibad.pytorch_ignite:INFO] Training model on device: mps
[2024-10-07 12:02:49,572 fibad.pytorch_ignite:INFO] Total epochs: 10
Current run is terminating due to exception: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/drew/opt/miniconda3/envs/fibad/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/opt/miniconda3/envs/fibad/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/opt/miniconda3/envs/fibad/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/Users/drew/opt/miniconda3/envs/fibad/lib/python3.11/site-packages/torchvision/datasets/cifar.py", line 119, in __getitem__
    img = self.transform(img)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/opt/miniconda3/envs/fibad/lib/python3.11/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
          ^^^^^^
  File "/Users/drew/opt/miniconda3/envs/fibad/lib/python3.11/site-packages/torchvision/transforms/transforms.py", line 137, in __call__
    return F.to_tensor(pic)
           ^^^^^^^^^^^^^^^^
  File "/Users/drew/opt/miniconda3/envs/fibad/lib/python3.11/site-packages/torchvision/transforms/functional.py", line 168, in to_tensor
    img = torch.from_numpy(np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected np.ndarray (got numpy.ndarray)
```

**Comment by drewoldag** [comment]
I initially got the same error when running with the autoencoder and a subset of the HSC data. I then deleted and recreated by conda environment, and now using the following config works as expected. 

```
[general]
use_gpu = true
log_destination = "stderr"
log_level = "info"
data_dir = "./data/hsc-samples"
results_dir = "./results"

[download]
sw = "22asec"
sh = "22asec"
filter = [ "HSC-G", "HSC-R", "HSC-I", "HSC-Z", "HSC-Y",]
type = "coadd"
rerun = "pdr3_wide"
username = false
password = false
num_sources = -1
offset = 0
concurrent_connections = 4
stats_print_interval = 60
fits_file = "./catalog.fits"
retry_wait = 30
retries = 3
timeout = 3600
chunk_size = 990
image = true
variance = false
mask = false

[model]
name = "ExampleAutoencoder"
weights_filepath = "example_model.pth"
epochs = 10
base_channel_size = 32
latent_dim = 64

[data_set]
name = "HSCDataSet"

[data_loader]
crop_to = false
filters = false
batch_size = 4
shuffle = true
num_workers = 2

[predict]
model_weights_file = false
batch_size = 32
```

**Comment by drewoldag** [comment]
Ok, and repeating the experiment with the CiFAR data, that now works as expected as well, using this config file.

```
[general]
use_gpu = true
log_destination = "stderr"
log_level = "info"
data_dir = "./data/hsc-samples"
results_dir = "./results"

[download]
sw = "22asec"
sh = "22asec"
filter = [ "HSC-G", "HSC-R", "HSC-I", "HSC-Z", "HSC-Y",]
type = "coadd"
rerun = "pdr3_wide"
username = false
password = false
num_sources = -1
offset = 0
concurrent_connections = 4
stats_print_interval = 60
fits_file = "./catalog.fits"
retry_wait = 30
retries = 3
timeout = 3600
chunk_size = 990
image = true
variance = false
mask = false

[model]
name = "ExampleAutoencoder"
weights_filepath = "example_model.pth"
epochs = 10
base_channel_size = 32
latent_dim = 64

[data_set]
name = "HSCDataSet"

[data_loader]
crop_to = false
filters = false
batch_size = 4
shuffle = true
num_workers = 2

[predict]
model_weights_file = false
batch_size = 32
```

**Comment by drewoldag** [comment]
I'm not exactly sure what to make of this other than to say that it seems like my environment somehow got into a strange state, and needed to be reset 🤷 

Not a very satisfying result, but it's good to confirm that @mtauraso's testing earlier was good.
