### ISSUE TITLE
error running on baldur (with GPU machines)

### ISSUE THREAD

**Issue by maxwest-uw** [lincc-frameworks/fibad#93]
**Bug report**
When running fibad on epyc (machine with not GPUs) I'm able to run my training fine. When running on baldur (machine with two gpus) I get the following error:
```
[2024-10-11 15:06:14,704 fibad:INFO] Runtime Config read from: kbmod_fibad_config.toml
/astro/users/maxwest/.conda/envs/kbmod-ml/lib/python3.10/site-packages/ignite/handlers/checkpoint.py:16: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import ZeroRedundancyOptimizer
<class 'kbmod_ml.models.resnet50.RESNET50'>
/astro/users/maxwest/.conda/envs/kbmod-ml/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/astro/users/maxwest/.conda/envs/kbmod-ml/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
2024-10-11 15:06:26,118 ignite.distributed.auto.auto_dataloader INFO: Use data loader kwargs for dataset '<kbmod_ml.data_sets.': 
	{'batch_size': 64, 'shuffle': True, 'num_workers': 8, 'pin_memory': True}
2024-10-11 15:06:26,466 ignite.distributed.auto.auto_model INFO: Apply torch DataParallel on model
2024-10-11 15:06:26,468 ignite.distributed.auto.auto_model INFO: Apply torch DataParallel on model
Traceback (most recent call last):
  File "/astro/users/maxwest/fibad_script.py", line 8, in <module>
    fibad_instance.train()
  File "/astro/users/maxwest/fibad/src/fibad/fibad.py", line 166, in train
    return run(config=self.config, **kwargs)
  File "/astro/users/maxwest/fibad/src/fibad/train.py", line 26, in run
    trainer = create_trainer(model)
  File "/astro/users/maxwest/fibad/src/fibad/pytorch_ignite.py", line 172, in create_trainer
    trainer = create_engine("train_step", device, model)
  File "/astro/users/maxwest/fibad/src/fibad/pytorch_ignite.py", line 113, in create_engine
    return Engine(_create_process_func(funcname, device, model))
  File "/astro/users/maxwest/fibad/src/fibad/pytorch_ignite.py", line 108, in _create_process_func
    inner_step = _extract_model_method(model, funcname)
  File "/astro/users/maxwest/fibad/src/fibad/pytorch_ignite.py", line 95, in _extract_model_method
    return getattr(model.module if wrapped else model, method_name)
  File "/astro/users/maxwest/.conda/envs/kbmod-ml/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DataParallel' object has no attribute 'train_step'
```
machine gpu info:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.06              Driver Version: 545.23.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:21:00.0  On |                  N/A |
| 27%   35C    P8              18W / 260W |     54MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:48:00.0 Off |                  N/A |
| 26%   28C    P8              13W / 260W |      1MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2354      G   /usr/bin/X                                   39MiB |
|    0   N/A  N/A      3618      G   /usr/bin/gnome-shell                         12MiB |
+---------------------------------------------------------------------------------------+
```

@drewoldag suggest that it could be a bad interaction with the GPUs, so leaving some info about that : )

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a description of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by drewoldag** [comment]
I think this might be due to the way we're trying to unwrap the DataParallel-wrapped model to get at the train_step method.

**Comment by drewoldag** [comment]
I was able to repro this using the current main branch on a Klone allocation with 2 gpus.
